version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
environment:
  NUGETAPIKEY:
    secure: eBKIUm4YxcrbL3oVC/ZCBUA/inEu+7OMbKpgftpOc18ievKNwH8UAUB2t4w+89Xv
  BUILD_BOT_PASSWORD:
    secure: U2EQbBdxNIC2FL8YeOP3bVixlZ4xLBdN71Szraw+ATqAhYZwEd6JCjCJZLJPu9kN
build_script:
- cmd: .\build.cmd publish "--trigger=%APPVEYOR_REPO_TAG_NAME%" "--branch=%APPVEYOR_REPO_BRANCH%" "--nuget-api-key=%NUGETAPIKEY%"
- sh: ./build.sh package
test: off
artifacts:
- path: 'release\*.nupkg'
