name: Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build Windows
      run: |
        $GitTag = [Regex]::Match($Env:GITHUB_REF, "^refs/tags/(.*)$").Groups[1].Value
        .\build.cmd publish "--trigger=$GitTag"
      if: runner.os == 'Windows'
    - name: Build Linux
      run: ./build.sh package
      if: runner.os == 'Linux'
