name: Build

on:
  push:
    branches:
      - '*'

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build
      run: .\build.cmd package

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build
      run: ./build.sh package
